### ISSUE TITLE
Intro Page - Eye Moved to the Left 

### ISSUE THREAD

**Issue by priyavprabhakar** [priyavprabhakar/thesis#1]
On the intro page, the eye is not centered in line with the text. It is too much to the right. 

![image](https://user-images.githubusercontent.com/8232531/70422822-3a257e00-1a21-11ea-8284-8a61f8869bb0.png)

**Comment by DivyaPrabhakar** [comment]
Fixed
![Uploading Screen Shot 2019-12-11 at 2.13.35 AM.png…]()

**Comment by DivyaPrabhakar** [comment]
Fixed
<img width="1440" alt="Screen Shot 2019-12-11 at 2 13 35 AM" src="https://user-images.githubusercontent.com/3968848/70612570-06329000-1bbc-11ea-9c4f-068bfd4895f0.png">
