### ISSUE TITLE
TextPanel Title Spacing

### ISSUE THREAD

**Issue by priyavprabhakar** [priyavprabhakar/thesis#2]
The titles of the TextPanel have too little space between them, could you make sure there's a little more space? (eg. between "Indian Telegraph" and "Law" in this image)

![image](https://user-images.githubusercontent.com/8232531/70422963-7ce75600-1a21-11ea-9e54-7fc97ac0a1ec.png)

**Comment by DivyaPrabhakar** [comment]
Before: 
<img width="363" alt="Screen Shot 2019-12-11 at 12 41 35 AM" src="https://user-images.githubusercontent.com/3968848/70605271-1001c680-1baf-11ea-833a-2f9deae98413.png">


After:
<img width="358" alt="Screen Shot 2019-12-11 at 12 41 40 AM" src="https://user-images.githubusercontent.com/3968848/70605300-1c861f00-1baf-11ea-96f3-6dc79834f35b.png">

Done
