### ISSUE TITLE
Hyperlinks in the ArchivalItem 

### ISSUE THREAD

**Issue by priyavprabhakar** [priyavprabhakar/thesis#3]
When you click the ArchivalItem, I want there to be two hyperlinks: one for the title and another for the date. When you click the title, I want the photo to enlarge with a panel to the side with the same writing, like this: 

![image](https://user-images.githubusercontent.com/8232531/70423858-30047f00-1a23-11ea-9c02-046904fbc6e5.png)
![image](https://user-images.githubusercontent.com/8232531/70423873-37c42380-1a23-11ea-9c2a-3fb08e71f901.png)

(If not possible, don't worry about it. I would at least like the title to be hyperlinked and lead to another website, which is the source website with more information that I will be adding to the database.)

**Comment by DivyaPrabhakar** [comment]
Done

**Comment by DivyaPrabhakar** [comment]
Updated version: 

Click the `x` to close the text overall
<img width="306" alt="Screen Shot 2019-12-11 at 12 38 12 AM" src="https://user-images.githubusercontent.com/3968848/70605148-c1542c80-1bae-11ea-83d6-3535d234f6cb.png">


Click the title to get this
<img width="1440" alt="Screen Shot 2019-12-11 at 12 40 07 AM" src="https://user-images.githubusercontent.com/3968848/70605196-df219180-1bae-11ea-8f3e-c34852f7ac61.png">
