### ISSUE TITLE
Hyperlinked in the "About" Panel 

### ISSUE THREAD

**Issue by priyavprabhakar** [priyavprabhakar/thesis#4]
I want all the links in the "About" panel to be hyperlinked:

priyaprabhakar32@gmail.com
@priyavprabhakar
https://github.com/priyavprabhakar/thesis

**Comment by DivyaPrabhakar** [comment]
Done

**Comment by DivyaPrabhakar** [comment]
<img width="1440" alt="Screen Shot 2019-12-11 at 12 38 45 AM" src="https://user-images.githubusercontent.com/3968848/70605084-a84b7b80-1bae-11ea-814f-f0b999d1778a.png">

Updated screenshot
