### ISSUE TITLE
Create Intro Context Pages

### ISSUE THREAD

**Issue by priyavprabhakar** [priyavprabhakar/thesis#5]
Totally fine if you cannot do this, but I thought I would ask. While doing more research, I realized I wanted my audience to be able to have some context before they enter the timeline. I created these mockups of 4 pages before they enter the timeline. It's just text, a button, and an image of the logo at the top (the eye). I attached all the pages here. 

![image](https://user-images.githubusercontent.com/8232531/70530254-54398c00-1b07-11ea-9cde-1f8105ce2ed6.png)

![image](https://user-images.githubusercontent.com/8232531/70530260-5a2f6d00-1b07-11ea-9536-22e2ac311ec7.png)

![image](https://user-images.githubusercontent.com/8232531/70530267-5e5b8a80-1b07-11ea-805e-3fdc2ef4762a.png)

![image](https://user-images.githubusercontent.com/8232531/70530278-63b8d500-1b07-11ea-9a16-733906995e3c.png)

![image](https://user-images.githubusercontent.com/8232531/70530285-67e4f280-1b07-11ea-896a-68877b7dc90b.png)

**Comment by DivyaPrabhakar** [comment]
Done and ready
