### ISSUE TITLE
Create Submission Button 

### ISSUE THREAD

**Issue by priyavprabhakar** [priyavprabhakar/thesis#6]
This is a lot to ask, once again, but if possible I would want a simple submission box, you can put it as a third option on the bottom where "About" and "Resources" are, and this is roughly what it would look like (just for your benefit if you are down to do it. If not, no worries. 

![image](https://user-images.githubusercontent.com/8232531/70530993-e68e5f80-1b08-11ea-8b86-379b6f1538b7.png)

**Comment by DivyaPrabhakar** [comment]
My suggestion for this is create a google form with these fields that submits directly to your email address. Then include a link in the footer "submit" that directs to that google form.
