### ISSUE TITLE
Create Submission Button

### ISSUE THREAD

**Issue by priyavprabhakar** [priyavprabhakar/thesis#7]
Could you possibly create a third section at the bottom that says "Submission"? And when you click it, can it be hyperlinked to this website: https://form.jotform.com/193446307997170

**Comment by DivyaPrabhakar** [comment]
Done

<img width="1440" alt="Screen Shot 2019-12-11 at 11 59 45 PM" src="https://user-images.githubusercontent.com/3968848/70693494-697ef980-1c72-11ea-94a4-6c4bd7bcdf25.png">
