### ISSUE TITLE
Size of Dates & Length 

### ISSUE THREAD

**Issue by priyavprabhakar** [priyavprabhakar/thesis#8]
Can you change the size of the dates at the top (a couple of sizes larger) and make sure it's more spread out (closer to the logo)? I know I reduced the number of dates, so that's why it shrunk. 

![image](https://user-images.githubusercontent.com/8232531/70667717-6f4eed80-1c26-11ea-8ee9-f7453b457b61.png)

**Comment by DivyaPrabhakar** [comment]
Done
